# Generated by Django 5.1.6 on 2025-03-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.IntegerField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiador',
            fields=[
                ('id_financiador', models.IntegerField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.IntegerField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equipe', models.ManyToManyField(to='app.colaboradores')),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areastecnologicas')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financiador')),
            ],
        ),
    ]
