# Generated by Django 5.1.6 on 2025-03-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areastecnologicas',
            options={'verbose_name': 'Área Tecnológica', 'verbose_name_plural': 'Áreas Tecnológicas'},
        ),
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='financiador',
            options={'verbose_name': 'Financiador', 'verbose_name_plural': 'Financiadores'},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
