# Generated by Django 5.1.6 on 2025-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_areastecnologicas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areastecnologicas',
            name='area_tecnologica',
            field=models.CharField(max_length=100, verbose_name='Área Tecnológica'),
        ),
        migrations.AlterField(
            model_name='areastecnologicas',
            name='id_area_tecnologica',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Área Tecnológica'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='id_colaborador',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do Colaborador'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='financiador',
            name='financiador',
            field=models.CharField(max_length=100, verbose_name='Financiador'),
        ),
        migrations.AlterField(
            model_name='financiador',
            name='id_financiador',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do Financiador'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='coordenador',
            field=models.CharField(max_length=100, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='equipe',
            field=models.ManyToManyField(to='app.colaboradores', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Vigência'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='id_projeto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do Projeto'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='inicio_vigencia',
            field=models.DateField(verbose_name='Início da Vigência'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='projeto',
            field=models.CharField(max_length=100, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
    ]
