# Generated by Django 5.1.6 on 2025-03-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_areastecnologicas_area_tecnologica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='id_area_tecnologica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areastecnologicas', verbose_name='Área Tecnológica'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='id_financiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financiador', verbose_name='Financiador'),
        ),
    ]
